#!/usr/bin/env python3
"""Board-project epics that had work in a sprint-end window (mirrors the Epic Reports
pivot), pinned as a saved Jira filter. Project comes from config (sources.yaml).

Jira can't roll child work-items up to their epics in native JQL (no ScriptRunner
issueFunction here), so we compute the epic set via the API and store it as a
`key in (...)` filter. Re-run to refresh when the window rolls.

The pivot set = epics that EITHER:
  - are the parent of a Done / "Mobile Release Pending" Story/Task/Bug whose
    resolution_sprint_end falls in (start, end), OR
  - carry an "Epic Planning Cycle" in the given cycle labels.

Usage:
  .venv/bin/python derive/pivot_epics.py                       # dry-run (prints JQL + count)
  .venv/bin/python derive/pivot_epics.py --apply               # create/update the saved filter
  .venv/bin/python derive/pivot_epics.py --start 2026-05-16 --end 2026-07-05 \
      --cycles May-26,Jun-26 --apply
"""
from __future__ import annotations
import argparse
import base64
import json
import sys
import urllib.parse
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from derive import capacity_engine as ce  # noqa: E402

FILTER_NAME = f"{ce.JIRA_PROJECT} · epics with work in window (pivot)"


def _auth() -> str:
    email, token = ce._secret("atlassian_email"), ce._secret("atlassian_token")
    return "Basic " + base64.b64encode(f"{email}:{token}".encode()).decode()


def _api(method: str, path: str, body=None):
    data = json.dumps(body).encode() if body is not None else None
    req = urllib.request.Request(f"https://{ce.JIRA_HOST}{path}", data=data, method=method)
    req.add_header("Authorization", _auth())
    if data is not None:
        req.add_header("Content-Type", "application/json")
    raw = urllib.request.urlopen(req, timeout=45).read()
    return json.loads(raw) if raw else {}


def _search(jql: str, fields):
    out, tok, pages = [], None, 0
    while True:
        body = {"jql": jql, "fields": fields, "maxResults": 100}
        if tok:
            body["nextPageToken"] = tok
        d = _api("POST", "/rest/api/3/search/jql", body)
        out += d.get("issues", [])
        tok = d.get("nextPageToken")
        pages += 1
        if d.get("isLast") or not tok or pages > 50:
            break
    return out


def epic_keys(start: str, end: str, cycles):
    proj = ce.JIRA_PROJECT
    keys = set()
    # A: parents of Done / MRP work items resolved (by sprint-end) in the window
    children = _search(
        f'project = {proj} AND resolution_sprint_end > "{start}" AND resolution_sprint_end < "{end}" '
        f'AND resolution_sprint_end is not EMPTY AND issuetype in (Story,Task,Bug) '
        f'AND status in (Done,"Mobile Release Pending")', ["parent"])
    parents = {(i.get("fields") or {}).get("parent", {}).get("key") for i in children}
    parents.discard(None)
    a_epics = 0
    if parents:
        for ep in _search(f"key in ({','.join(sorted(parents))}) AND issuetype = Epic", ["summary"]):
            keys.add(ep["key"]); a_epics += 1
    # B: epics tagged with the planning cycle(s)
    b_epics = 0
    if cycles:
        clause = ", ".join(cycles)
        for ep in _search(f'project = {proj} AND issuetype = Epic AND "Epic Planning Cycle" in ({clause})',
                          ["summary"]):
            keys.add(ep["key"]); b_epics += 1
    return sorted(keys), len(children), a_epics, b_epics


def upsert_filter(jql: str):
    found = _api("GET", "/rest/api/3/filter/search?filterName="
                 + urllib.parse.quote(FILTER_NAME) + "&expand=jql")
    mine = next((f for f in found.get("values", []) if f.get("name") == FILTER_NAME), None)
    body = {"name": FILTER_NAME, "jql": jql,
            "description": "Auto-generated by derive/pivot_epics.py — board-project epics with "
                           "work done in the pivot window (native JQL can't roll children up to "
                           "epics). Re-run the script to refresh."}
    if mine:
        _api("PUT", f"/rest/api/3/filter/{mine['id']}", body)
        return mine["id"], "updated"
    body["favourite"] = True
    r = _api("POST", "/rest/api/3/filter", body)
    return r["id"], "created"


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--start", default="2026-05-16")
    ap.add_argument("--end", default="2026-07-05")
    ap.add_argument("--cycles", default="May-26,Jun-26",
                    help="comma-separated Epic Planning Cycle labels, or '' to skip")
    ap.add_argument("--apply", action="store_true", help="create/update the saved Jira filter")
    args = ap.parse_args()
    cycles = [c.strip() for c in args.cycles.split(",") if c.strip()]

    keys, n_children, a_epics, b_epics = epic_keys(args.start, args.end, cycles)
    sys.stderr.write(f"window {args.start}..{args.end} | done work items: {n_children} | "
                     f"parent epics: {a_epics} | planning-cycle epics: {b_epics} | "
                     f"total unique: {len(keys)}\n")
    if not keys:
        sys.stderr.write("no epics matched — not writing an empty filter\n")
        return
    jql = (f"project = {ce.JIRA_PROJECT} AND issuetype = Epic "
           f"AND key in ({','.join(keys)}) ORDER BY key ASC")
    print(jql)
    if args.apply:
        fid, action = upsert_filter(jql)
        url = f"https://{ce.JIRA_HOST}/issues/?filter={fid}"
        sys.stderr.write(f"filter {action}: id={fid}\n{url}\n")


if __name__ == "__main__":
    main()
